# Generated by Django 4.2.10 on 2024-03-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_additionalinfoflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='birth_year',
            field=models.IntegerField(default=2000),
        ),
    ]
