# Generated by Django 4.2.10 on 2024-03-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_passwordresetmode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usergroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'member'), name='duplicate_group_member'),
        ),
    ]
