# Generated by Django 5.0.1 on 2024-02-26 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapists', '0001_initial'),
        ('therapy', '0001_initial'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.DateTimeField()),
                ('session_type', models.CharField(choices=[('First Session', 'First Session'), ('Recurring Session', 'Recurring Session')], default='First Session', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=20)),
                ('is_free', models.BooleanField(default=False)),
                ('session_completed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='therapists.therapistmeetinglink')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='therapists.therapist')),
                ('therapy_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='therapy.therapytype')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utils.tracker')),
            ],
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('client', 'slot'), name='multiple_same_date_time_appointment'),
        ),
    ]
