# Generated by Django 4.2.10 on 2024-03-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='therapistexperience',
            constraint=models.UniqueConstraint(fields=('therapist', 'year_started'), name='duplicate_year'),
        ),
        migrations.AddConstraint(
            model_name='therapistexpertise',
            constraint=models.UniqueConstraint(fields=('therapist', 'field'), name='duplicate_expertise_field'),
        ),
        migrations.AddConstraint(
            model_name='therapistmeetinglink',
            constraint=models.UniqueConstraint(fields=('therapist', 'link'), name='duplicate_link'),
        ),
        migrations.AddConstraint(
            model_name='therapistqualification',
            constraint=models.UniqueConstraint(fields=('therapist', 'qualification'), name='duplicate_qualification'),
        ),
        migrations.AddConstraint(
            model_name='therapistworkplace',
            constraint=models.UniqueConstraint(fields=('therapist', 'workplace'), name='duplicate_workplace'),
        ),
    ]
