# Generated by Django 4.2.10 on 2024-03-20 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('therapists', '0002_therapistexperience_duplicate_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='therapistexperience',
            name='therapist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='therapists.therapist'),
        ),
        migrations.AlterField(
            model_name='therapistmeetinglink',
            name='therapist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='therapists.therapist'),
        ),
        migrations.AlterField(
            model_name='therapistprofilepicture',
            name='therapist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='therapists.therapist'),
        ),
    ]
