# Generated by Django 4.2.10 on 2024-03-24 17:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('html_id', models.CharField(max_length=20)),
                ('copy', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
