# Generated by Django 4.2.10 on 2024-03-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_copy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Copy',
        ),
    ]
