# Generated by Django 4.2.10 on 2024-03-31 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name_plural': 'Policies'},
        ),
    ]
