# Generated by Django 5.0.1 on 2024-02-26 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('therapists', '0001_initial'),
        ('therapy', '0001_initial'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('first_session', models.IntegerField(default=25, verbose_name='For first sessions (%)')),
                ('recurring_session', models.IntegerField(default=25, verbose_name='For recurring sessions (%)')),
            ],
            options={
                'verbose_name_plural': 'Commission',
            },
        ),
        migrations.CreateModel(
            name='BaseSessionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_session', models.IntegerField(default=0, verbose_name='First sessions (BDT)')),
                ('recurring_session', models.IntegerField(default=0, verbose_name='Recurring sessions (BDT)')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapists.therapist')),
                ('therapy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.therapytype')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('transaction_id', models.CharField(default='N/A', max_length=50)),
                ('is_closed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utils.tracker')),
            ],
        ),
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('description', models.TextField(default='...')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.commission')),
                ('therapy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.therapytype')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usergroup')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_payable', models.BooleanField(default=True)),
                ('payable_amount', models.IntegerField(default=0)),
                ('is_discounted', models.BooleanField(default=False)),
                ('applied_discount', models.IntegerField(default=0)),
                ('applied_commission', models.IntegerField(default=25)),
                ('applied_user_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.usergroup')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utils.tracker')),
                ('applied_price_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finances.pricegroup')),
            ],
        ),
        migrations.CreateModel(
            name='PriceGroupTherapistMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_session_therapist_discount', models.IntegerField(default=0, verbose_name='Discount for first sessions (%)')),
                ('recurring_session_therapist_discount', models.IntegerField(default=0, verbose_name='Discount for recurring sessions (%)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.pricegroup')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapists.therapist')),
            ],
        ),
    ]
