# Generated by Django 4.2.10 on 2024-03-10 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_personalinfo_birth_year'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_amount', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('is_free', models.BooleanField(default=False, verbose_name='Free')),
                ('is_counted', models.BooleanField(default=False, verbose_name='Counted')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.usergroup')),
            ],
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='applied_promo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='finances.promo'),
        ),
    ]
