# Generated by Django 4.2.10 on 2024-03-10 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
        ('finances', '0002_promo_paymentinfo_applied_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='therapy_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='therapy.therapytype'),
        ),
    ]
