# Generated by Django 4.2.10 on 2024-03-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_rename_max_amount_promo_deductable_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='deductable_amount',
            new_name='max_deductable_amount',
        ),
        migrations.AlterField(
            model_name='promo',
            name='retrieval_limit',
            field=models.IntegerField(default=0, help_text='If limit is zero (0) it means there is no limit.'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='user_retrieval_limit',
            field=models.IntegerField(default=0, help_text='If limit is zero (0) it means there is no limit.'),
        ),
    ]
