# Generated by Django 4.2.10 on 2024-03-14 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_alter_personalinfo_birth_year'),
        ('utils', '0001_initial'),
        ('finances', '0006_rename_deductable_amount_promo_max_deductable_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='applied_price_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='finances.pricegroup'),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='applied_user_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.usergroup'),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='tracker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='utils.tracker'),
        ),
    ]
