# Generated by Django 4.2.10 on 2024-03-27 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_copy'),
        ('finances', '0007_paymentinfo_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.tracker'),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='tracker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='utils.tracker'),
        ),
    ]
