# Generated by Django 4.2.10 on 2024-03-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_alter_invoice_tracker_alter_paymentinfo_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='payable_to_therapist',
            field=models.IntegerField(default=0),
        ),
    ]
