# Generated by Django 4.2.10 on 2024-03-28 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_paymentinfo_payable_to_therapist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='applied_promo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finances.promo'),
        ),
    ]
