# Generated by Django 4.2.10 on 2024-03-28 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_alter_paymentinfo_applied_promo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentinfo',
            options={'verbose_name': 'Payment Info', 'verbose_name_plural': 'Payment Info'},
        ),
    ]
