# Generated by Django 4.2.10 on 2024-03-30 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_delete_copy'),
        ('finances', '0011_alter_paymentinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tracker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utils.tracker'),
        ),
    ]
