# Generated by Django 4.2.10 on 2024-05-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_alter_invoice_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='display_price',
            field=models.IntegerField(default=0),
        ),
    ]
