# Generated by Django 5.0.1 on 2024-02-26 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')], default=0)),
                ('hour', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapists.therapist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='therapistschedule',
            constraint=models.UniqueConstraint(fields=('therapist', 'weekday', 'hour', 'minute'), name='unique_schedule'),
        ),
    ]
