# Generated by Django 4.2.10 on 2024-04-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DASS21Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('domain', models.CharField(choices=[('Depression', 'Depression'), ('Anxiety', 'Anxiety'), ('Stress', 'Stress')], max_length=20)),
            ],
            options={
                'verbose_name': 'DASS-21 Test Question',
                'verbose_name_plural': 'DASS-21 Test Questions',
            },
        ),
    ]
